name: Delete Branch After Merge

on:
  pull_request:
    types: [closed]


jobs:
  my_job:
    runs-on: windows-latest
    env:
          GITHUB_TOKEN: "${{ secrets.YOUR_PAT_SECRET }}"
          GITHUB_INSTANCE_URL: "https://github.com"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          git push origin --delete branch-to-delete
       
          
