name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Git
        run: |
          git config --global user.name "RewGuardiano"
          git config --global user.email "rew.guardiano@students.ittralee.ie"

      - name: Delete branch
        run: |
          git push origin --delete branch-to-delete
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
