name: Delete Branch After Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete_branch:
    runs-on: windows-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          git config --global user.name "RewGuardiano"
          git config --global user.email "rew.guardiano@students.ittralee.ie"
          git push origin --delete ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
