name: Deploying Volunteering System

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"


      - name: Install Netlify CLI
        run: npm install -g netlify-cli 

      - name: Install dependencies for frontend and backend
        run: |
          cd connecting-kerry
          npm install
          cd connecting-kerry/app_api 
          npm install

      - name: Build React app
        run: |
          cd connecting-kerry
          npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}  

      - name: Initialize Netlify
        run: netlify init
  
  
      - name: Deploy to Netlify
        run: |
          cd ..
          netlify deploy --prod --dir=client/build --functions=server --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      

         
