name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install backend dependencies
      working-directory: connecting-kerry/app_api
      run: npm install

    - name: Install frontend dependencies
      working-directory: connecting-kerry/frontend
      run: npm install

    - name: Build frontend
      working-directory: connecting-kerry/frontend
      run: npm run build

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        publish-dir: connecting-kerry/frontend/build
        production-branch: main
        deploy-message: 'Deploying frontend and backend as serverless functions'
      env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        
    - name: Display Deployment URL
      run: echo "Netlify Deployment URL - https://connectingkerry.netlify.app/"
      id: display_url
      
    - name: Set URL as Output
      run: echo "::set-output name=url::https://connectingkerry.netlify.app/"
      id: set_output

