name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install backend dependencies
      working-directory: connecting-kerry/app_api
      run: npm install

    - name: Install frontend dependencies
      working-directory: connecting-kerry/frontend
      run: npm install

    - name: Build frontend
      working-directory: connecting-kerry/frontend
      run: npm run build

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: connecting-kerry/frontend/build
        production-branch: main
        deploy-message: 'Deploying frontend and backend as serverless functions'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
